# Generated by Django 3.2.3 on 2021-05-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0003_logdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logDB',
            new_name='LOG_DB',
        ),
    ]
