# Generated by Django 3.2.3 on 2021-05-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0003_log_db'),
        ('aladin', '0004_rename_logdb_log_db'),
    ]

    operations = [
    ]
