# Generated by Django 3.2.3 on 2021-05-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksnapshot',
            name='author',
            field=models.CharField(default='NAN', max_length=30),
        ),
        migrations.AddField(
            model_name='booksnapshot',
            name='name',
            field=models.CharField(default='NAN', max_length=50),
        ),
    ]
