# Generated by Django 3.2.3 on 2021-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='', max_length=20)),
                ('book_title', models.CharField(default='', max_length=30)),
                ('book_author', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedBookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20)),
                ('ordered_book_id', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=50)),
            ],
        ),
    ]
