# Generated by Django 3.2.3 on 2021-05-29 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='userdeliveryinfo',
            name='user_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='OrderedBookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('books', models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, related_name='book', to='prepare.book')),
            ],
        ),
    ]
