# Generated by Django 3.2.3 on 2021-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0002_rename_user_id_orderedbooklist_ordered_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orderedbooklist',
            name='ordered_book_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderedbooklist',
            name='ordered_user_id',
            field=models.CharField(max_length=20),
        ),
    ]
